export const AWS_CONFIG_KEY = 'AWS';
export const GCP_CONFIG_KEY = 'GCP';
export const OPENAI_API_KEY_CONFIG_KEY = 'OPENAI_API_KEY';
export const DATABASE_URL_CONFIG_KEY = 'DATABASE_URL';
export const ENABLE_EMAIL_SERVICE_CONFIG_KEY = 'ENABLE_EMAIL_SERVICE';
export const JWT_SECRET_CONFIG_KEY = 'JWT_SECRET';
export const JWT_EXPIRATION_TIME_CONFIG_KEY = 'JWT_EXPIRATION_TIME';
export const REFRESH_TOKEN_EXPIRATION_TIME_CONFIG_KEY =
  'REFRESH_TOKEN_EXPIRATION_TIME';
export const REDIS_HOST_CONFIG_KEY = 'REDIS_HOST';
export const REDIS_PORT_CONFIG_KEY = 'REDIS_PORT';
