export const AWS_CONFIG_KEY = 'AWS';
export const DEFAULT_CATEGORY_ID_CONFIG_KEY = 'DEFAULT_CATEGORY_ID';
export const DATABASE_URL_CONFIG_KEY = 'DATABASE_URL';
export const ENABLE_EMAIL_SERVICE_CONFIG_KEY = 'ENABLE_EMAIL_SERVICE';
export const GCP_CONFIG_KEY = 'GCP';
export const JWT_SECRET_CONFIG_KEY = 'JWT_SECRET';
export const JWT_EXPIRATION_TIME_CONFIG_KEY = 'JWT_EXPIRATION_TIME';
export const NODE_ENV_CONFIG_KEY = 'NODE_ENV';
export const OPENAI_API_KEY_CONFIG_KEY = 'OPENAI_API_KEY';
export const REFRESH_TOKEN_EXPIRATION_TIME_CONFIG_KEY =
  'REFRESH_TOKEN_EXPIRATION_TIME';
export const REDIS_URL_CONFIG_KEY = 'REDIS_URL';
export const ACCEPT_INVITE_REDIRECT_URL_CONFIG_KEY =
  'ACCEPT_INVITE_REDIRECT_URL';
export const RESET_PASSWORD_REDIRECT_URL_CONFIG_KEY =
  'RESET_PASSWORD_REDIRECT_URL';
