/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type CurrencyCode = 'HKD' | 'PHP' | 'THB' | 'USD' | 'VND';

export type ExpenseSource = 'api' | 'import' | 'manual' | 'ocr';

export type ExpenseStatus = 'draft' | 'pending' | 'rejected' | 'verified';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrganizationType = 'business' | 'personal';

export type PermissionAction =
  | 'create'
  | 'delete'
  | 'manage'
  | 'read'
  | 'update';

export type PermissionResource =
  | 'categories'
  | 'expenses'
  | 'organizations'
  | 'users';

export type ProcessingStatus =
  | 'completed'
  | 'failed'
  | 'pending'
  | 'processing';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = 'business_admin' | 'member' | 'personal_admin';

export interface Auth {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  password: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Categories {
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  is_default: Generated<boolean>;
  name: string;
  organization_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface Expenses {
  amount: Numeric;
  category_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: Generated<CurrencyCode>;
  date: Timestamp;
  description: string | null;
  id: Generated<string>;
  import_id: string | null;
  items: Json | null;
  llm_result_id: string | null;
  merchant_name: string;
  ocr_result_id: string | null;
  organization_id: string;
  other_details: Json | null;
  photos: string[] | null;
  source: ExpenseSource;
  status: Generated<ExpenseStatus>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  user_id: string;
  verified_by: string | null;
}

export interface Imports {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  error_details: Json | null;
  failed_rows: Generated<number>;
  file: string;
  id: Generated<string>;
  organization_id: string;
  processed_rows: Generated<number>;
  status: Generated<ProcessingStatus>;
  successful_rows: Generated<number>;
  total_rows: number | null;
  user_id: string;
}

export interface Invites {
  created_at: Generated<Timestamp>;
  created_by: string;
  email: string;
  expires_at: Generated<Timestamp>;
  id: Generated<string>;
  organization_id: string;
  role_id: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  used: Generated<boolean>;
  used_at: Timestamp | null;
}

export interface LlmResults {
  created_at: Generated<Timestamp>;
  error_message: string | null;
  extracted_data: Json | null;
  id: Generated<string>;
  ocr_result_id: string;
  processing_time_ms: number | null;
  status: Generated<ProcessingStatus>;
  updated_at: Generated<Timestamp>;
}

export interface Merchants {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  normalized_name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface OcrResults {
  confidence_score: Numeric | null;
  created_at: Generated<Timestamp>;
  entities: Json | null;
  error_message: string | null;
  id: Generated<string>;
  image_path: string;
  ocr_text: string | null;
  organization_id: string;
  processing_time_ms: number | null;
  status: Generated<ProcessingStatus>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Organizations {
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  name: string;
  type: Generated<OrganizationType>;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface Permissions {
  action: PermissionAction;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  resource: PermissionResource;
  updated_at: Generated<Timestamp>;
}

export interface RolePermissions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  permission_id: string;
  role_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Roles {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: UserRole;
  updated_at: Generated<Timestamp>;
}

export interface UserOrganizations {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  organization_id: string;
  role_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  first_name: string | null;
  id: Generated<string>;
  last_name: string | null;
  middle_name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  auth: Auth;
  categories: Categories;
  expenses: Expenses;
  imports: Imports;
  invites: Invites;
  llm_results: LlmResults;
  merchants: Merchants;
  ocr_results: OcrResults;
  organizations: Organizations;
  permissions: Permissions;
  role_permissions: RolePermissions;
  roles: Roles;
  user_organizations: UserOrganizations;
  users: Users;
}
