name: Production Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/feenex-backend
            git pull origin main
            yarn install --production --frozen-lockfile
            yarn build
            pm2 restart feenex-backend
            pm2 save
